"""create countries table

Revision ID: 27011cfbfeba
Revises: 
Create Date: 2026-07-09 00:28:50.968852

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27011cfbfeba'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('countries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('actor_type', sa.Enum('STATE', 'INTERNATIONAL_ORG', 'MILITARY_ALLIANCE', name='actortype'), nullable=False),
    sa.Column('geopolitical_bloc', sa.Enum('WEST', 'EAST', 'EU', 'NEUTRAL', name='geopoliticalbloc'), nullable=True),
    sa.Column('recognized_kosovo', sa.Boolean(), nullable=True),
    sa.Column('country_code', sa.String(length=3), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_countries_id'), 'countries', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_countries_id'), table_name='countries')
    op.drop_table('countries')
    # ### end Alembic commands ###
