"""require indicator source, default is_verified false

Revision ID: 45d07387185e
Revises: 77c12298b0d5
Create Date: 2026-08-21 18:10:48.447946

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45d07387185e'
down_revision: Union[str, Sequence[str], None] = '77c12298b0d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators', 'source',
               existing_type=sa.VARCHAR(length=200),
               nullable=False)
    # ### end Alembic commands ###
    # Χειροκίνητη προσθήκη (compare_server_default δεν είναι ενεργό στο
    # env.py, άρα το autogenerate δεν το έπιασε) -- soft source-check
    # business rule: νέα indicators μη-επαληθευμένα by default, βλ.
    # schemas/indicator.py IndicatorCreate.is_verified.
    op.alter_column('indicators', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'))


def downgrade() -> None:
    """Downgrade schema."""
    op.alter_column('indicators', 'is_verified',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('true'))
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('indicators', 'source',
               existing_type=sa.VARCHAR(length=200),
               nullable=True)
    # ### end Alembic commands ###
