"""add supporter role, supports_country_id, role_description

Revision ID: 77c12298b0d5
Revises: b536861761e3
Create Date: 2026-08-05 20:07:42.132618

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77c12298b0d5'
down_revision: Union[str, Sequence[str], None] = 'b536861761e3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Χειροκίνητη προσθήκη -- το Alembic autogenerate ΔΕΝ ανιχνεύει νέες τιμές
    # σε υπάρχον Postgres ENUM type (μόνο add/drop column/table). Το
    # 'PARTY'/'MEDIATOR'/'GUARANTOR' και τα υπάρχοντα rows μένουν ανέπαφα --
    # το ADD VALUE απλώς επεκτείνει το επιτρεπόμενο σύνολο τιμών.
    op.execute("ALTER TYPE participantrole ADD VALUE IF NOT EXISTS 'SUPPORTER'")

    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('countries', sa.Column('role_description', sa.Text(), nullable=True))
    op.add_column('event_participants', sa.Column('supports_country_id', sa.Integer(), nullable=True))
    op.create_foreign_key(
        'fk_event_participants_supports_country_id_countries',
        'event_participants', 'countries', ['supports_country_id'], ['id'],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        'fk_event_participants_supports_country_id_countries',
        'event_participants', type_='foreignkey',
    )
    op.drop_column('event_participants', 'supports_country_id')
    op.drop_column('countries', 'role_description')
    # ### end Alembic commands ###

    # ΣΗΜΕΙΩΣΗ: δεν αφαιρείται το 'SUPPORTER' από το participantrole enum --
    # η Postgres δεν υποστηρίζει DROP VALUE σε ENUM type χωρίς να ξαναφτιαχτεί
    # ολόκληρος ο τύπος (και μόνο αν καμία γραμμή δεν το χρησιμοποιεί πια).
    # Ασφαλής παράλειψη: μια επιπλέον επιτρεπόμενη τιμή που δεν χρησιμοποιείται
    # δεν έχει καμία επίπτωση.
