"""create negotiation_events and event_participants tables

Revision ID: ff5f350e2aa4
Revises: 51bb723cd8d8
Create Date: 2026-07-29 13:30:46.813442

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff5f350e2aa4'
down_revision: Union[str, Sequence[str], None] = '51bb723cd8d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('zopa_size', sa.Enum('NARROW', 'MODERATE', 'WIDE', name='zopasize'), nullable=True),
    sa.Column('zopa_reasoning', sa.Text(), nullable=True),
    sa.Column('ripeness_status', sa.Enum('NOT_RIPE', 'EMERGING', 'RIPE', name='ripenessstatus'), nullable=True),
    sa.Column('ripeness_reasoning', sa.Text(), nullable=True),
    sa.Column('batna_side_a', sa.Text(), nullable=True),
    sa.Column('batna_side_b', sa.Text(), nullable=True),
    sa.Column('red_lines_side_a', sa.Text(), nullable=True),
    sa.Column('red_lines_side_b', sa.Text(), nullable=True),
    sa.Column('negotiation_type', sa.Enum('DISTRIBUTIVE', 'INTEGRATIVE_WIN_WIN', name='negotiationtype'), nullable=True),
    sa.Column('economic_weight', sa.Integer(), nullable=False),
    sa.Column('military_weight', sa.Integer(), nullable=False),
    sa.Column('social_weight', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_events_id'), 'negotiation_events', ['id'], unique=False)
    op.create_table('event_participants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('country_id', sa.Integer(), nullable=False),
    sa.Column('role', sa.Enum('PARTY', 'MEDIATOR', 'GUARANTOR', name='participantrole'), nullable=False),
    sa.ForeignKeyConstraint(['country_id'], ['countries.id'], ),
    sa.ForeignKeyConstraint(['event_id'], ['negotiation_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_participants_id'), 'event_participants', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_participants_id'), table_name='event_participants')
    op.drop_table('event_participants')
    op.drop_index(op.f('ix_negotiation_events_id'), table_name='negotiation_events')
    op.drop_table('negotiation_events')
    # ### end Alembic commands ###
