"""create negotiation_analyses table

Revision ID: ff99ad846894
Revises: 64b3d95665c7
Create Date: 2026-08-02 13:51:04.862372

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ff99ad846894'
down_revision: Union[str, Sequence[str], None] = '64b3d95665c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('negotiation_analyses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('negotiation_event_id', sa.Integer(), nullable=True),
    sa.Column('is_synthesis', sa.Boolean(), nullable=False),
    sa.Column('user_question', sa.Text(), nullable=False),
    sa.Column('llm_answer', sa.Text(), nullable=True),
    sa.Column('model_used', sa.String(length=100), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['negotiation_event_id'], ['negotiation_events.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_negotiation_analyses_id'), 'negotiation_analyses', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_negotiation_analyses_id'), table_name='negotiation_analyses')
    op.drop_table('negotiation_analyses')
    # ### end Alembic commands ###
