import { useMutation } from "@tanstack/react-query";
import { createSynthesis } from "../api/negotiationAnalyses";
import { QuestionForm } from "../components/QuestionForm";
import { LLMAnswerCard } from "../components/LLMAnswerCard";
import { ErrorState } from "../components/ui";

// POST /synthesis: LLM ερμηνεία πάνω σε ΟΛΑ τα events + scores μαζί
// (is_synthesis=true, negotiation_event_id=NULL). Βλ. CLAUDE.md "LLM
// integration" -- temperature=0, το context είναι πάντα δομημένα δεδομένα
// του backend, ποτέ ελεύθερη γνώση του μοντέλου.
export function SynthesisPage() {
  const mutation = useMutation({ mutationFn: createSynthesis });

  return (
    <div>
      <h1>Synthesis</h1>
      <p>
        Ask a question about the negotiation record as a whole. The answer is generated by an
        LLM strictly from the structured data already in this platform (all events, power-index
        scores, optimal periods) -- it never introduces facts or figures of its own.
      </p>

      <QuestionForm
        onSubmit={(question) => mutation.mutate({ user_question: question })}
        isSubmitting={mutation.isPending}
        placeholder="e.g. Which negotiation window offered Kosovo the most leverage, and why?"
      />

      {mutation.isError && <ErrorState error={mutation.error} />}
      {mutation.isSuccess && (
        <div style={{ marginTop: "1rem" }}>
          <LLMAnswerCard analysis={mutation.data} variant="synthesis" />
        </div>
      )}
    </div>
  );
}
